name: Analyze
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙ Install moreutils (for sponge)
        run: sudo apt-get update && sudo apt-get install -y moreutils

      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 📋 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: 🚥 Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 💾 Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: 🔗 Install dependencies
        run: |
          cp composer.json composer.json.bak
          jq 'del(.require["shopware/core"], .require["shopware/storefront"])' composer.json | sponge composer.json
          composer install --prefer-dist
          rm composer.json composer.lock && mv composer.json.bak composer.json

      - name: 🪮 Check code style
        run: composer style-check

      - name: 📋 Check licenses of dependencies
        run: composer check-licenses
